#!/bin/bash
#PBS -lnodes=1
#PBS -lwalltime=100:00:00
file=Bayestwin 
echo Hello, I will now run $file.R in folder $file, one moment please...
cd $HOME/$file || exit
module load R
export R_LIBS=$HOME/rpackages:$R_LIBS
R --save --no-restore < $file.R > $file.output
mv .RData $file.workspace
echo Ready... Have a good day!







